//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Pose SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchPad
        {
            get
            {
                return SteamVR_Actions.default_TouchPad;
            }
        }
        
        public virtual SteamVR_Action_Vector3 TouchPosition
        {
            get
            {
                return SteamVR_Actions.default_TouchPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean Up
        {
            get
            {
                return SteamVR_Actions.default_Up;
            }
        }
        
        public virtual SteamVR_Action_Boolean Down
        {
            get
            {
                return SteamVR_Actions.default_Down;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left
        {
            get
            {
                return SteamVR_Actions.default_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right
        {
            get
            {
                return SteamVR_Actions.default_Right;
            }
        }
        
        public virtual SteamVR_Action_Pose Camera
        {
            get
            {
                return SteamVR_Actions.default_Camera;
            }
        }
        
        public virtual SteamVR_Action_Pose Position
        {
            get
            {
                return SteamVR_Actions.default_Position;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
